Controllers/LOC_CON_ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using DatabaseFetchData.Models;

namespace DatabaseFetchData.Controllers
{
    public class LOC_CON_ContactController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public LOC_CON_ContactController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        #endregion

        #region SelectAll
        public IActionResult Index()
        {
            String str = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_CON_Contact_SelectAll";
            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);
            return View("LOC_CON_ContactList", dt);
        }
        #endregion .

        #region Delete
        public IActionResult Delete(int ContactID)
        {
            String str = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand = new SqlConnection(str);
            objCommand.Open();
            SqlCommand objCommand2 = objCommand.CreateCommand();
            objCommand2.CommandType = System.Data.CommandType.StoredProcedure;
            objCommand2.CommandText = "PR_LOC_CON_Contact_DeleteByPK";
            objCommand2.Parameters.AddWithValue("@ContactID", ContactID);
            objCommand2.ExecuteNonQuery();
            return RedirectToAction("Index");
        }
        #endregion

        #region Add
        public IActionResult Add(int? ContactID)
        {
            #region DropDown -> Country
            String str1 = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand1 = new SqlConnection(str1);
            objCommand1.Open();
            SqlCommand cmd1 = objCommand1.CreateCommand();
            cmd1.CommandType = System.Data.CommandType.StoredProcedure;
            cmd1.CommandText = "LOC_Country_DropDown";
            /*cmd1.Parameters.Add("@CountryID", SqlDbType.Int).Value = CountryID;*/
            DataTable dt1 = new DataTable();
            SqlDataReader sdr1 = cmd1.ExecuteReader();
            dt1.Load(sdr1);
            objCommand1.Close();
            List<LOC_CountryDropDownModel> vlst = new List<LOC_CountryDropDownModel>();
            foreach (DataRow dr1 in dt1.Rows)
            {
                LOC_CountryDropDownModel v = new LOC_CountryDropDownModel();
                v.CountryID = Convert.ToInt32(dr1["CountryID"]);
                v.CountryName = Convert.ToString(dr1["CountryName"]);
                vlst.Add(v);
            }
            ViewBag.LOC_CountryList = vlst;
            #endregion

            #region DropDown -> State
            /*String str2 = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand2 = new SqlConnection(str2);
            objCommand2.Open();
            SqlCommand cmd2 = objCommand2.CreateCommand();
            cmd2.CommandType = System.Data.CommandType.StoredProcedure;
            cmd2.CommandText = "LOC_State_DropDown";
            DataTable dt2 = new DataTable();
            SqlDataReader sdr2 = cmd2.ExecuteReader();
            dt2.Load(sdr2);
            objCommand2.Close();*/
            List<LOC_StateDropDownModel> vlst1 = new List<LOC_StateDropDownModel>();
            /*foreach (DataRow dr2 in dt2.Rows)
            {
                LOC_StateDropDownModel v1 = new LOC_StateDropDownModel();
                v1.StateID = Convert.ToInt32(dr2["StateID"]);
                v1.StateName = Convert.ToString(dr2["StateName"]);
                vlst1.Add(v1);
            }*/
            ViewBag.LOC_StateList = vlst1;
            #endregion

            #region DropDown -> City
            /*String str3 = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand3 = new SqlConnection(str3);
            objCommand3.Open();
            SqlCommand cmd3 = objCommand3.CreateCommand();
            cmd3.CommandType = System.Data.CommandType.StoredProcedure;
            cmd3.CommandText = "LOC_City_DropDown";
            DataTable dt3 = new DataTable();
            SqlDataReader sdr3 = cmd3.ExecuteReader();
            dt3.Load(sdr3);
            objCommand3.Close();*/
            List<LOC_CityDropDownModel> vlst2 = new List<LOC_CityDropDownModel>();
            /*foreach (DataRow dr2 in dt3.Rows)
            {
                LOC_CityDropDownModel v1 = new LOC_CityDropDownModel();
                v1.CityID = Convert.ToInt32(dr2["CityID"]);
                v1.CityName = Convert.ToString(dr2["CityName"]);
                vlst2.Add(v1);
            }*/
            ViewBag.LOC_CityList = vlst2;
            #endregion

            #region DropDown -> ContactCategory
            String str4 = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand4 = new SqlConnection(str4);
            objCommand4.Open();
            SqlCommand cmd4 = objCommand4.CreateCommand();
            cmd4.CommandType = System.Data.CommandType.StoredProcedure;
            cmd4.CommandText = "LOC_MST_ContactCategory_DropDown";
            DataTable dt4 = new DataTable();
            SqlDataReader sdr4 = cmd4.ExecuteReader();
            dt4.Load(sdr4);
            objCommand4.Close();
            List<LOC_MST_ContactCategoryDropDownModel> vlst3 = new List<LOC_MST_ContactCategoryDropDownModel>();
            foreach (DataRow dr2 in dt4.Rows)
            {
                LOC_MST_ContactCategoryDropDownModel v1 = new LOC_MST_ContactCategoryDropDownModel();
                v1.ContactCategoryID = Convert.ToInt32(dr2["ContactCategoryID"]);
                v1.ContactCategoryName = Convert.ToString(dr2["ContactCategoryName"]);
                vlst3.Add(v1);
            }
            ViewBag.LOC_ContactCategoryList = vlst3;
            #endregion

            #region Select By PK
            if (ContactID != null)
            {
                String str = this.Configuration.GetConnectionString("MyConnectionStrings");
                SqlConnection objCommand = new SqlConnection(str);
                objCommand.Open();
                SqlCommand cmd = objCommand.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_LOC_CON_Contact_SelectByPK";
                cmd.Parameters.Add("@ContactID", SqlDbType.Int).Value = ContactID;
                DataTable dt = new DataTable();
                SqlDataReader sdr = cmd.ExecuteReader();
                dt.Load(sdr);

                LOC_CON_ContactModel modelLOC_CON_Contact = new LOC_CON_ContactModel();
                foreach (DataRow dr in dt.Rows)
                {
                    modelLOC_CON_Contact.ContactID = Convert.ToInt32(dr["ContactID"]);
                    modelLOC_CON_Contact.ContactName = dr["ContactName"].ToString();
                    modelLOC_CON_Contact.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelLOC_CON_Contact.StateID = Convert.ToInt32(dr["StateID"]);
                    modelLOC_CON_Contact.CityID = Convert.ToInt32(dr["CityID"]);
                    modelLOC_CON_Contact.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                    modelLOC_CON_Contact.Address = dr["Address"].ToString();
                    modelLOC_CON_Contact.PinCode = Convert.ToInt32(dr["PinCode"]);
                    modelLOC_CON_Contact.Mobile = Convert.ToInt32(dr["Mobile"]);
                    modelLOC_CON_Contact.AlternetContact = Convert.ToInt32(dr["AlternetContact"]);
                    modelLOC_CON_Contact.Email = dr["Email"].ToString();
                    modelLOC_CON_Contact.BirthDate = Convert.ToDateTime(dr["BirthDate"]);
                    modelLOC_CON_Contact.LinkedIn = dr["LinkedIn"].ToString();
                    modelLOC_CON_Contact.Twitter = dr["Twitter"].ToString();
                    modelLOC_CON_Contact.Insta = dr["Insta"].ToString();
                    modelLOC_CON_Contact.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                    modelLOC_CON_Contact.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);
                }

                return View("LOC_CON_ContactAddEdit", modelLOC_CON_Contact);

            }
            #endregion

            return View("LOC_CON_ContactAddEdit");
        }
        #endregion

        #region Save
        public IActionResult Save(LOC_CON_ContactModel modelLOC_CON_Contact)
        {
            if (ModelState.IsValid)
            {
                String str = this.Configuration.GetConnectionString("MyConnectionStrings");
                SqlConnection objCommand = new SqlConnection(str);
                objCommand.Open();
                SqlCommand cmd = objCommand.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                if (modelLOC_CON_Contact.ContactID == null)
                {
                    cmd.CommandText = "PR_LOC_CON_Contact_Insert";
                    cmd.Parameters.Add("@CreationDate", SqlDbType.Date).Value = modelLOC_CON_Contact.CreationDate;

                }
                else
                {
                    cmd.CommandText = "PR_LOC_CON_Contact_UpdateByPK";
                    cmd.Parameters.Add("@ContactID", SqlDbType.Int).Value = modelLOC_CON_Contact.ContactID;
                }
                cmd.Parameters.Add("@ContactName", SqlDbType.VarChar).Value = modelLOC_CON_Contact.ContactName;
                cmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = modelLOC_CON_Contact.CountryID;

Views/LOC_CON_Contact/LOC_CON_ContactList.cshtml
@{
    ViewData["Title"] = "State List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data
@model DataTable

<div class="row">
    <div class="col col-md-10">
        <h1>Contact List</h1>
    </div>
    <div class="pull-right">
        <div id="sample_1_filter" class="dataTables_filter">
            <label><input type="text" class="form-control input-sm input-small input-inline" placeholder="Search" id="sample_1" aria-controls="sample_1" /></label>
        </div>
    </div>
    <div class="col col-md-2">
        <a class="btn btn-success" asp-controller="LOC_CON_Contact" asp-action="Add">ADD LIST</a>
    </div>
</div>
<hr />

<table class="table" id="sample_1">
    <thead>
        <tr>
            <th scope="col" colspan="2" class="text-center">Action</th>
            @*<th scope="col">Contact ID        </th>*@
            <th scope="col">ContactCategory Name      </th>
            <th scope="col">Contact Name      </th>
            <th scope="col">Country Name     </th>
            <th scope="col">State Name     </th>
            <th scope="col">City Name    </th>
            <th scope="col"> Address    </th>
            <th scope="col">PinCode </th>
            <th scope="col">Mobile </th>
            <th scope="col">AlternetContact </th>
            <th scope="col"> Email</th>
            <th scope="col"> BirthDate</th>
            <th scope="col"> LinkedIn</th>
            <th scope="col"> Twitter</th>
            <th scope="col"> Insta</th>
            <th scope="col">CreationDate </th>
            <th scope="col">ModificationDate </th>

        </tr>
    </thead>
    <tbody id="sample_2">
        @foreach (DataRow dr in Model.Rows)

        {
            <tr>
                <td scope="col">
                    <form method="post" asp-controller="LOC_CON_Contact" asp-action="Delete">
                        <input type="hidden" name="ContactID" value="@Convert.ToInt32(dr["ContactID"])" />
                        <button type="submit" class="btn btn-danger" onclick="return confirm ('Are you sure you want to delete : @dr["ContactName"]')">Delete</button>
                    </form>
                </td>
                <td scope="col">
                    <form method="post" asp-controller="LOC_CON_Contact" asp-action="Add">
                        <input type="hidden" name="ContactID" value="@Convert.ToInt32(dr["ContactID"])" />
                        <button type="submit" class="btn btn-success">Edit</button>
                    </form>
                </td>
                @*<th scope="col">@dr["ContactID"]</th>*@
                <td scope="col"> @dr["ContactCategoryName"]   </td>
                <td scope="col"> @dr["ContactName"]   </td>
                <td scope="col"> @dr["CountryName"]   </td>
                <td scope="col"> @dr["StateName"]   </td>
                <td scope="col"> @dr["CityName"]   </td>
                <td scope="col"> @dr["Address"]   </td>
                <td scope="col"> @dr["PinCode"]   </td>
                <td scope="col"> @dr["Mobile"]   </td>
                <td scope="col"> @dr["AlternetContact"]   </td>
                <td scope="col"> @dr["Email"]   </td>
                <td scope="col"> @dr["BirthDate"]   </td>
                <td scope="col"> @dr["LinkedIn"]   </td>
                <td scope="col"> @dr["Twitter"]   </td>
                <td scope="col"> @dr["Insta"]   </td>
                <td scope="col"> @Convert.ToDateTime(dr["CreationDate"]).ToString("dd-MM-yyyy")</td>
                <td scope="col"> @Convert.ToDateTime(dr["ModificationDate"]).ToString("dd-MM-yyyy")</td>
                
            </tr>
        }
    </tbody>
</table>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}