Controllers/LOC_CityController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using DatabaseFetchData.Models;
using DatabaseFetchData.Dal;

namespace DatabaseFetchData.Controllers
{
    public class LOC_CityController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public LOC_CityController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        #endregion

        #region SelectAll
        public IActionResult Index()
        {

            String str = this.Configuration.GetConnectionString("MyConnectionStrings");
            LOC_Dal dalLOC = new LOC_Dal();
            DataTable dt = dalLOC.dbo_PR_LOC_City_SelectAll(str);
            return View("LOC_CityList", dt);

            /*SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_City_SelectAll";
            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);*/


        }
        #endregion

        #region Delete
        public IActionResult Delete(int CityID)
        {
            String str = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand = new SqlConnection(str);
            objCommand.Open();
            SqlCommand objCommand2 = objCommand.CreateCommand();
            objCommand2.CommandType = System.Data.CommandType.StoredProcedure;
            objCommand2.CommandText = "PR_LOC_City_DeleteByPK";
            objCommand2.Parameters.AddWithValue("@CityID", CityID);
            objCommand2.ExecuteNonQuery();
            return RedirectToAction("Index");
        }
        #endregion

        #region AddEdit
        public IActionResult Add(int? CityID)
        {


            #region DropDown => Country
            String str2 = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand2 = new SqlConnection(str2);
            objCommand2.Open();
            SqlCommand cmd2 = objCommand2.CreateCommand();
            cmd2.CommandType = System.Data.CommandType.StoredProcedure;
            cmd2.CommandText = "LOC_Country_DropDown";
            DataTable dt2 = new DataTable();
            SqlDataReader sdr2 = cmd2.ExecuteReader();
            dt2.Load(sdr2);

            List<LOC_CountryDropDownModel> list1 = new List<LOC_CountryDropDownModel>();
            foreach (DataRow dr1 in dt2.Rows)
            {
                LOC_CountryDropDownModel model = new LOC_CountryDropDownModel();
                model.CountryID = Convert.ToInt32(dr1["CountryID"]);
                model.CountryName = Convert.ToString(dr1["CountryName"]);
                list1.Add(model);
            }
            ViewBag.CountryList = list1;
            #endregion

            #region DropDown => State
            /*String str1 = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand1 = new SqlConnection(str1);
            objCommand1.Open();
            SqlCommand cmd1 = objCommand1.CreateCommand();
            cmd1.CommandType = System.Data.CommandType.StoredProcedure;
            cmd1.CommandText = "LOC_State_DropDown";
            *//*cmd1.Parameters.Add("@CountryID", SqlDbType.Int).Value = CountryID*//*
            ;
            DataTable dt1 = new DataTable();
            SqlDataReader sdr1 = cmd1.ExecuteReader();
            dt1.Load(sdr1);*/

            List<LOC_StateDropDownModel> list = new List<LOC_StateDropDownModel>();
            /*foreach (DataRow dr1 in dt1.Rows)
            {
                LOC_StateDropDownModel model = new LOC_StateDropDownModel();
                model.StateID = Convert.ToInt32(dr1["StateID"]);
                model.StateName = Convert.ToString(dr1["StateName"]);
                list.Add(model);
            }*/
            ViewBag.StateList = list;
            #endregion

            #region Select By PK
            if (CityID != null)
            {
                String str = this.Configuration.GetConnectionString("MyConnectionStrings");
                SqlConnection objCommand = new SqlConnection(str);
                objCommand.Open();
                SqlCommand cmd = objCommand.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_LOC_City_SelectByPK";
                cmd.Parameters.Add("@CityID", SqlDbType.Int).Value = CityID;
                DataTable dt = new DataTable();
                SqlDataReader sdr = cmd.ExecuteReader();
                dt.Load(sdr);

                LOC_CityModel modelLOC_City = new LOC_CityModel();

                foreach (DataRow dr in dt.Rows)
                {
                    modelLOC_City.CityID = Convert.ToInt32(dr["CityID"]);
                    modelLOC_City.CityName = dr["CityName"].ToString();
                    modelLOC_City.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelLOC_City.StateID = Convert.ToInt32(dr["StateID"]);
                    modelLOC_City.PinCode = Convert.ToInt32(dr["PinCode"]);
                    modelLOC_City.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);
                }
                return View("LOC_CityAddEdit", modelLOC_City);

            }
            #endregion

            return View("LOC_CityAddEdit");
        }
        #endregion

        #region Save
        public IActionResult Save(LOC_CityModel modelLOC_City)
        {
            if (ModelState.IsValid)
            {
                String str = this.Configuration.GetConnectionString("MyConnectionStrings");
                SqlConnection objCommand = new SqlConnection(str);
                objCommand.Open();
                SqlCommand cmd = objCommand.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                if (modelLOC_City.CityID == null)
                {
                    cmd.CommandText = "PR_LOC_City_Insert";
                    cmd.Parameters.Add("@CreationDate", SqlDbType.Date).Value = modelLOC_City.CreationDate;


                }
                else
                {
                    cmd.CommandText = "PR_LOC_City_UpDateByPK";
                    cmd.Parameters.Add("@CityID", SqlDbType.Int).Value = modelLOC_City.CityID;


                }
                cmd.Parameters.Add("@CityName", SqlDbType.VarChar).Value = modelLOC_City.CityName;
                cmd.Parameters.Add("@PinCode", SqlDbType.Int).Value = modelLOC_City.PinCode;
                cmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = modelLOC_City.CountryID;
                cmd.Parameters.Add("@StateID", SqlDbType.Int).Value = modelLOC_City.StateID;
                cmd.Parameters.Add("@ModificationDate", SqlDbType.Date).Value = modelLOC_City.ModificationDate;

                if (Convert.ToBoolean(cmd.ExecuteNonQuery()))
                {
                    if (modelLOC_City.CityID == null)
                    {
                        TempData["message"] = "Record Inserted Successsfully";
                    }
                    else
                    {
                        TempData["message"] = "Record Updated Successsfully";
                    }
                }
                objCommand.Close();
            }
            return RedirectToAction("Add");
        }
        #endregion

        #region cascaded DropDownByState => state
        public IActionResult DropDownByState(int CountryID)
        {
            String str1 = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand1 = new SqlConnection(str1);
            objCommand1.Open();
            SqlCommand cmd1 = objCommand1.CreateCommand();
            cmd1.CommandType = System.Data.CommandType.StoredProcedure;
            cmd1.CommandText = "LOC_State_DropDown";
            cmd1.Parameters.AddWithValue("@CountryID", CountryID);
            DataTable dt1 = new DataTable();
            SqlDataReader sdr1 = cmd1.ExecuteReader();
            dt1.Load(sdr1);
            objCommand1.Close();

            List<LOC_StateDropDownModel> list = new List<LOC_StateDropDownModel>();
            foreach (DataRow dr1 in dt1.Rows)
            {
                LOC_StateDropDownModel model = new LOC_StateDropDownModel();
                model.StateID = Convert.ToInt32(dr1["StateID"]);
                model.StateName = Convert.ToString(dr1["StateName"]);
                list.Add(model);
            }

            var VModel = list;
            return Json(VModel);
        }
        #endregion
    }
}

Views/LOC_City/LOC_CityAddEdit.cshtml
@{
    ViewData["Title"] = "City Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


@model LOC_CityModel

@*<div class="row">
    <div class="col-md-12">
        <h2>@TempData["message"]</h2>
        &nbsp;
        <form method="post" asp-controller="LOC_City" asp-action="Save">
            @Html.HiddenFor(x=>x.CityID)
            <div class="from-group">
                <label>Country Name</label>
                <select class="form-control" asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))" onchange="(stateChange())">
                    <option value="">Select Country</option>
                </select>
            </div>
            <div class="from-group">
                <label>State Name</label>
                <select class="form-control" asp-for="StateID" asp-items="@(new SelectList(ViewBag.StateList,"StateID","StateName"))">
                    <option value="">Select State</option>
                </select>
            </div>
            <div class="from-group">
                <label>City Name</label>
                <input type="text" class="from-Control" placeholder="Enter City Name" asp-for="CityName" />
            </div>
            <div class="from-group">
                <label>City Code</label>
                <input type="text" class="from-Control" placeholder="Enter City PinCode" asp-for="PinCode" />
            </div>

            <div class="from-group">
                <label>Creation Date</label>
                <input type="date" class="from-Control" placeholder="Enter Creation Date" asp-for="CreationDate" />
            </div>
            <div class="from-group">
                <label>Modification Date</label>
                <input type="date" class="from-Control" placeholder="Enter Modification Date" asp-for="ModificationDate" />
            </div>
            </hr>
            <input type="submit" />
            <button asp-controller="LOC_City" asp-action="Add">Clear</button>
            <button asp-controller="LOC_City" asp-action="Index">Back to CityList</button>
        </form>
    </div>

</div>*@

<style>
    .btn.btn-a {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-a:hover {
            background-color: #2eca6a;
            color: #000000;
        }

    .btn.btn-b {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-b:hover {
            background-color: rgba(255,0,0, 1);
            color: #ffffff;
        }
</style>

<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">City Add Edit</h1>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="LOC_City"><i class="fa-regular fa-address-book"></i> City List</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            City Add Edit
                        </li>
                    </ol>
                </nav>
            </div>
        </div>

        <hr />
        <br />
        <br />
    </div>


    <div class="container">
        <h5 style="color:green"><label>@TempData["message"]</label></h5>
        <br />
        <form method="post" asp-controller="LOC_City" asp-action="Save">
            @Html.HiddenFor(x=>x.CityID)

            <div class="row">
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    Country :-
                </div>
                <div class="col-md-3">
                    <select asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))" class="form-control" onchange="stateChange()">
                        <option value="">Select Country</option>
                    </select>
                    <span asp-validation-for="CountryID" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    State  :-
                </div>
                <div class="col-md-3">
                    <select asp-for="StateID" asp-items="@(new SelectList(ViewBag.StateList,"StateID","StateName"))" class="form-control">
                        <option value="">Select State</option>
                    </select>
                    <span asp-validation-for="StateID" class="text-danger"></span>
                </div>
            </div>
            <br />


            <div class="row">


                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    City Name :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter City Name" asp-for="CityName" class="form-control" />
                    <span asp-validation-for="CityName" class="text-danger"></span>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    Pin Code :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter Pin Code" asp-for="PinCode" class="form-control" />
                    <span asp-validation-for="PinCode" class="text-danger"></span>
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-md-2">
                    Creation Date :-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter Creation Date" asp-for="CreationDate" class="form-control" />
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    Modification Date :-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter Modification Date" asp-for="ModificationDate" class="form-control" />
                </div>
            </div>
            <br />


            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Save" asp-controller="LOC_City" asp-action="Save" class="btn btn-a" />
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Cancel" asp-controller="LOC_City" asp-action="Index" class="btn btn-b" />
                </div>
            </div>
        </form>

    </div>
</section>

<script>
    function stateChange() {
        var CountryID = $("#CountryID").val();

        if (CountryID !== "") {
            $("#StateID").empty();
            $("#StateID").append($("<option></option>").val("").html("Select State"));

            $.ajax(
                {
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    url: "@Url.Action("DropDownByState","LOC_City")" + "?&CountryID=" + CountryID,
                    data: {},
                    dataType: "json",
                    success: function (Result) {
                        $.each(Result,
                            function (key, value) {
                                $("#StateID").append($("<option></option>").val(value.stateID).html(value.stateName));
                            });
                    },
                    error: function (r) {
                        alert("Error while loading combobox.");
                    }
                });
        } else {
            $("#StateID").empty();
            $("#StateID").append($("<option></option>").val("").html("Select State"));

        }
    }
</script>

@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

                             

Views/LOC_City/LOC_CityList.cshtml
@{
    ViewData["Title"] = "State List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data
@model DataTable

<div class="row">
    <div class="col col-md-10">
        <h1>City List</h1>
    </div>
    <div class="pull-right">
        <div id="sample_1_filter" class="dataTables_filter">
            <label><input type="text" class="form-control input-sm input-small input-inline" placeholder="Search" id="sample_1" aria-controls="sample_1" /></label>
        </div>
    </div>
    <div class="col col-md-2">
        <a class="btn btn-success" asp-controller="LOC_City" asp-action="Add">ADD LIST</a>
    </div>
</div>
<hr />

<table class="table" id="sample_1">
    <thead>
        <tr>
            @*<th scope="col">City ID        </th>*@
            <th scope="col">City Name      </th>
            <th scope="col">PinCode      </th>
            <th scope="col">StateName      </th>
            <th scope="col">CountryName      </th>
            <th scope="col">Creation Date     </th>
            <th scope="col">Modification Date    </th>
            <th scope="col" colspan="2" class="text-center">Action</th>

        </tr>
    </thead>
    <tbody id="sample_2">
        @foreach (DataRow dr in Model.Rows)

        {
            <tr>

                @*<th scope="col">@dr["CityID"]</th>*@
                <td scope="col"> @dr["CityName"]                                            </td>
                <td scope="col"> @dr["PinCode"]                                            </td>
                <td scope="col"> @dr["StateName"]                                            </td>
                <td scope="col"> @dr["CountryName"]                                            </td>
                <td scope="col"> @Convert.ToDateTime(dr["CreationDate"]).ToString("dd-MM-yyyy")</td>
                <td scope="col"> @Convert.ToDateTime(dr["ModificationDate"]).ToString("dd-MM-yyyy")</td>
                <td scope="col">
                    <form method="post" asp-controller="LOC_City" asp-action="Delete">
                        <input type="hidden" name="CityID" value="@Convert.ToInt32(dr["CityID"])" />
                        <button type="submit" class="btn btn-danger" onclick="return confirm ('Are you sure you want to delete : @dr["CityName"]')">Delete</button>
                    </form>
                </td>
                <td scope="col">
                    <form method="post" asp-controller="LOC_City" asp-action="Add">
                        <input type="hidden" name="CityID" value="@Convert.ToInt32(dr["CityID"])" />
                        <button type="submit" class="btn btn-success">Edit</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}