Controllers/LOC_StateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using DatabaseFetchData.Models;
using DatabaseFetchData.Dal;

namespace DatabaseFetchData.Controllers
{
    public class LOC_StateController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public LOC_StateController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        #endregion

        #region SelectAll
        public IActionResult Index()
        {
            String str = this.Configuration.GetConnectionString("MyConnectionStrings");
            LOC_Dal dalLOC = new LOC_Dal();
            DataTable dt = dalLOC.dbo_PR_LOC_State_SelectAll(str);
            return View("LOC_StateList", dt);

            /*SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_State_SelectAll";
            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);*/

        }
        #endregion

        #region Delete
        public IActionResult Delete(int StateID)
        {
            String str = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand = new SqlConnection(str);
            objCommand.Open();
            SqlCommand objCommand2 = objCommand.CreateCommand();
            objCommand2.CommandType = System.Data.CommandType.StoredProcedure;
            objCommand2.CommandText = "PR_LOC_State_DeleteByPK";
            objCommand2.Parameters.AddWithValue("@StateID", StateID);
            objCommand2.ExecuteNonQuery();
            return RedirectToAction("Index");
        }
        #endregion

        #region Add
        public IActionResult Add(int? StateID)
        {
            #region DropDown

            String str1 = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand1 = new SqlConnection(str1);
            objCommand1.Open();
            SqlCommand cmd1 = objCommand1.CreateCommand();
            cmd1.CommandType = System.Data.CommandType.StoredProcedure;
            cmd1.CommandText = "LOC_Country_DropDown";
            DataTable dt1 = new DataTable();
            SqlDataReader sdr1 = cmd1.ExecuteReader();
            dt1.Load(sdr1);
            objCommand1.Close();

            List<LOC_CountryDropDownModel> list = new List<LOC_CountryDropDownModel>();
            foreach (DataRow dr in dt1.Rows)
            {
                LOC_CountryDropDownModel vlst = new LOC_CountryDropDownModel();
                vlst.CountryID = Convert.ToInt32(dr["CountryID"]);
                vlst.CountryName = dr["CountryName"].ToString();
                list.Add(vlst);
            }
            ViewBag.CountryList = list;
            #endregion

            #region Select By PK
            if (StateID != null)
            {
                String str = this.Configuration.GetConnectionString("MyConnectionStrings");
                SqlConnection objCommand = new SqlConnection(str);
                objCommand.Open();
                SqlCommand cmd = objCommand.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_LOC_State_SelectByPK";
                cmd.Parameters.Add("@StateID", SqlDbType.Int).Value = StateID;
                DataTable dt = new DataTable();
                SqlDataReader sdr = cmd.ExecuteReader();
                dt.Load(sdr);

                LOC_StateModel modelLOC_State = new LOC_StateModel();
                foreach (DataRow dr in dt.Rows)
                {
                    modelLOC_State.StateID = Convert.ToInt32(dr["StateID"]);
                    modelLOC_State.StateName = dr["StateName"].ToString();
                    modelLOC_State.StateCode = dr["StateCode"].ToString();
                    modelLOC_State.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelLOC_State.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                    modelLOC_State.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);
                }

                return View("LOC_StateAddEdit", modelLOC_State);

            }
            #endregion 
            return View("LOC_StateAddEdit");
        }
        #endregion

        #region Save
        public IActionResult Save(LOC_StateModel modelLOC_State)
        {
            if (ModelState.IsValid)
            {
                String str = this.Configuration.GetConnectionString("MyConnectionStrings");
                SqlConnection objCommand = new SqlConnection(str);
                objCommand.Open();
                SqlCommand cmd = objCommand.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;


                if (modelLOC_State.StateID == null)
                {
                    cmd.CommandText = "PR_LOC_State_Insert";
                    cmd.Parameters.Add("@CreationDate", SqlDbType.Date).Value = modelLOC_State.CreationDate;

                }
                else
                {
                    cmd.CommandText = "PR_LOC_State_UpdateByPK";
                    cmd.Parameters.Add("@StateID", SqlDbType.Int).Value = modelLOC_State.StateID;


                }

                cmd.Parameters.Add("@StateName", SqlDbType.NVarChar).Value = modelLOC_State.StateName;
                cmd.Parameters.Add("@StateCode", SqlDbType.NVarChar).Value = modelLOC_State.StateCode;
                cmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = modelLOC_State.CountryID;
                cmd.Parameters.Add("@ModificationDate", SqlDbType.Date).Value = modelLOC_State.ModificationDate;


                if (Convert.ToBoolean(cmd.ExecuteNonQuery()))
                {
                    if (modelLOC_State.StateID == null)
                    {
                        TempData["CountryInsertMsg"] = "Record Inserted Successsfully";
                    }
                    else
                    {
                        TempData["CountryInsertMsg"] = "Record Updated Successsfully";
                    }
                }
                objCommand.Close();
            }
            return RedirectToAction("Add");
        }
        #endregion
    }
}

Views/LOC_State/LOC_StateAddEdit.cshtml
@{
    ViewData["Title"] = "State Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


@model LOC_StateModel
 
<style>
    .btn.btn-a {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }
        .btn.btn-a:hover {
            background-color: #2eca6a;
            color: #000000;
        }
    .btn.btn-b {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }
        .btn.btn-b:hover {
            background-color: rgba(255,0,0, 1);
            color: #ffffff;
        }
</style>

<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h3 class="title-single">State Add Edit</h3>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="LOC_State"><i class="fa-regular fa-address-book"></i> State List</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            State Add Edit
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <hr />
       
    </div>


    <div class="container">
        <h5 style="color:green"><label>@TempData["CountryInsertMsg"]</label></h5>
        <br />
        <form method="post" asp-controller="LOC_State" asp-action="Save">
            @Html.HiddenFor(x=>x.StateID)
            <div class="row">

                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    Country :-
                </div>
                <div class="col-md-3">
                    <select asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))" class="form-control">
                        <option value="">Select Country</option>
                    </select>
                    <span asp-validation-for="CountryID" class="text-danger"></span>

                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    State Name :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter State Name" asp-for="StateName" class="form-control" />
                    <span asp-validation-for="StateName" class="text-danger"></span>
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    State Code :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter State Code" asp-for="StateCode" class="form-control" />
                    <span asp-validation-for="StateCode" class="text-danger"></span>

                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    Creation Date :-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter CreationDate Date" asp-for="CreationDate" class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    Modification Date:-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter Modification Date" asp-for="ModificationDate" class="form-control" />
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    @*<span style="color: #ff0000">*</span>*@
                    @*Creation *@
                </div>
                <div class="col-md-3">
                    @*<input type="date" placeholder="Enter Modification Date" asp-for="CreationDate" class="form-control" />*@
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Save" asp-controller="LOC_State" asp-action="Save" class="btn btn-a" />
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Cancel" asp-controller="LOC_State" asp-action="Index" class="btn btn-b" />
                </div>
            </div>
        </form>

    </div>
</section><!-- End Intro Single-->
@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/LOC_State/LOC_StateList.cshtml
@using System.Data
@model DataTable

<div class="row">
    <div class="col col-md-10">
        <h1>State List</h1>
    </div>
    <div class="pull-right">
        <div id="sample_1_filter" class="dataTables_filter">
            <label><input type="text" class="form-control input-sm input-small input-inline" placeholder="Search" id="sample_1" aria-controls="sample_1" /></label>
        </div>
    </div>
    <div class="col col-md-2">
        <a class="btn btn-success" asp-controller="LOC_State" asp-action="Add">ADD LIST</a>
    </div>
</div>
<hr />
<table class="table" id="sample_1">
    <thead>
        <tr>
            @*<th scope="col">State ID        </th>*@
            <th scope="col">State Name      </th>
            <th scope="col">State Code      </th>
            <th scope="col">Country Name      </th>
            <th scope="col">Creation Date     </th>
            <th scope="col">Modification Date    </th>
            <th scope="col" colspan="2" class="text-center">Action</th>

        </tr>
    </thead>
    <tbody id="sample_2">
        @foreach (DataRow dr in Model.Rows)

        {
            <tr>

                @*<th scope="col">@dr["StateID"]</th>*@
                <td scope="col"> @dr["StateName"]                                            </td>
                <td scope="col"> @dr["StateCode"]                                            </td>
                <td scope="col"> @dr["CountryName"]                                            </td>
                <td scope="col"> @Convert.ToDateTime(dr["CreationDate"]).ToString("dd-MM-yyyy")</td>
                <td scope="col"> @Convert.ToDateTime(dr["ModificationDate"]).ToString("dd-MM-yyyy")</td>
                <td scope="col">
                    <form method="post" asp-controller="LOC_State" asp-action="Delete">
                        <input type="hidden" name="StateID" value="@Convert.ToInt32(dr["StateID"])" />
                        <button type="submit" class="btn btn-danger" onclick="return confirm ('Are you sure you want to delete : @dr["StateName"]')">Delete</button>
                    </form>
                </td>
                <td scope="col">
                    <form method="post" asp-controller="LOC_State" asp-action="Add">
                        <input type="hidden" name="StateID" value="@Convert.ToInt32(dr["StateID"])" />
                        <button type="submit" class="btn btn-success">Edit</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}


    