Controllers/LOC_MST_ContactCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using DatabaseFetchData.Models;

namespace DatabaseFetchData.Controllers
{
    public class LOC_MST_ContactCategoryController : Controller
    {
        #region Configuration
        private IConfiguration Configuration;
        public LOC_MST_ContactCategoryController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        #endregion

        #region SelectAll
        public IActionResult Index()
        {
            String str = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_MST_ContactCategory_SelectAll";
            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);
            return View("LOC_MST_ContactCategoryList", dt);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int ContactCategoryID)
        {
            String str = this.Configuration.GetConnectionString("MyConnectionStrings");
            SqlConnection objCommand = new SqlConnection(str);
            objCommand.Open();
            SqlCommand objCommand2 = objCommand.CreateCommand();
            objCommand2.CommandType = System.Data.CommandType.StoredProcedure;
            objCommand2.CommandText = "PR_LOC_MST_ContactCategory_DeleteByPK";
            objCommand2.Parameters.AddWithValue("@ContactCategoryID", ContactCategoryID);
            objCommand2.ExecuteNonQuery();
            return RedirectToAction("Index");
        }
        #endregion

        #region Add
        public IActionResult Add(int? ContactCategoryID)
        {
            if (ContactCategoryID != null)
            {
                String str = this.Configuration.GetConnectionString("MyConnectionStrings");
                SqlConnection objCommand = new SqlConnection(str);
                objCommand.Open();
                SqlCommand cmd = objCommand.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_LOC_MST_ContactCategory_SelectByPK";
                cmd.Parameters.Add("@ContactCategoryID", SqlDbType.Int).Value = ContactCategoryID;
                DataTable dt = new DataTable();
                SqlDataReader sdr = cmd.ExecuteReader();
                dt.Load(sdr);

                LOC_MST_ContactCategoryModel modelLOC_MST_ContactCategory = new LOC_MST_ContactCategoryModel();

                foreach (DataRow dr in dt.Rows)
                {
                    modelLOC_MST_ContactCategory.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                    modelLOC_MST_ContactCategory.ContactCategoryName = dr["ContactCategoryName"].ToString();
                    modelLOC_MST_ContactCategory.CreationDate = Convert.ToDateTime(dr["CreationDate"]);
                    modelLOC_MST_ContactCategory.Modification = Convert.ToDateTime(dr["Modification"]);

                }
                return View("LOC_MST_ContactCategoryAddEdit", modelLOC_MST_ContactCategory);

            }
            return View("LOC_MST_ContactCategoryAddEdit");
        }
        #endregion

        #region Save
        public IActionResult Save(LOC_MST_ContactCategoryModel modelLOC_MST_ContactCategory)
        {
            if (ModelState.IsValid)
            {
                String str = this.Configuration.GetConnectionString("MyConnectionStrings");
                SqlConnection objCommand = new SqlConnection(str);
                objCommand.Open();
                SqlCommand cmd = objCommand.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                if (modelLOC_MST_ContactCategory.ContactCategoryID == 0)
                {
                    cmd.CommandText = "PR_LOC_MST_ContactCategory_Insert";
                    cmd.Parameters.Add("@CreationDate", SqlDbType.Date).Value = modelLOC_MST_ContactCategory.CreationDate;

                }
                else
                {
                    cmd.CommandText = "PR_LOC_MST_ContactCategory_UpDateByPK";
                    cmd.Parameters.Add("@ContactCategoryID", SqlDbType.Int).Value = modelLOC_MST_ContactCategory.ContactCategoryID;

                }
                cmd.Parameters.Add("@ContactCategoryName", SqlDbType.VarChar).Value = modelLOC_MST_ContactCategory.ContactCategoryName;
                cmd.Parameters.Add("@Modification", SqlDbType.Date).Value = modelLOC_MST_ContactCategory.Modification;

                if (Convert.ToBoolean(cmd.ExecuteNonQuery()))
                {
                    if (modelLOC_MST_ContactCategory.ContactCategoryID == 0)
                    {
                        TempData["message"] = "Record Inserted Successsfully";
                    }
                    else
                    {
                        TempData["message"] = "Record Updated Successsfully";
                    }
                }
                objCommand.Close();
            }
            return RedirectToAction("Add");
        }
        #endregion
    }
}

Views/LOC_MST_ContactCategory/LOC_MST_ContactCategoryAddEdit.cshtml
@{
    ViewData["Title"] = "ContactCategory Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@model LOC_MST_ContactCategoryModel

@*<div class="row">
    <div class="col-md-12">
        <h2>@TempData["message"]</h2>
        &nbsp;
        <form method="post" asp-controller="LOC_MST_ContactCategory" asp-action="Save">
            @Html.HiddenFor(x=>x.ContactCategoryID)

            <div class="from-group">
                <label>ContactCategory Name</label>
                <input type="text" class="from-Control" placeholder="Enter ContactCategory Name" asp-for="ContactCategoryName" />
            </div>
            <div class="from-group">
                <label>Creation Date</label>
                <input type="date" class="from-Control" placeholder="Enter Creation Date" asp-for="CreationDate" />
            </div>
            <div class="from-group">
                <label>Modification Date</label>
                <input type="date" class="from-Control" placeholder="Enter Modification Date" asp-for="Modification" />
            </div>
            </hr>
            <input type="submit" />
            <button asp-controller="LOC_MST_ContactCategory" asp-action="Add">Clear</button>
            <button asp-controller="LOC_MST_ContactCategory" asp-action="Index">Back to ContactCategoryList</button>
        </form>
    </div>

</div>*@


<style>
    .btn.btn-a {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-a:hover {
            background-color: #2eca6a;
            color: #000000;
        }

    .btn.btn-b {
        text-decoration: none;
        background-color: #000000;
        color: #ffffff;
    }

        .btn.btn-b:hover {
            background-color: rgba(255,0,0, 1);
            color: #ffffff;
        }
</style>


<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">ContactCategory Add Edit</h1>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="LOC_MST_ContactCategory"><i class="fa-regular fa-address-book"></i> ContactCategory List</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            ContactCategory Add Edit
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <hr />
        <br />
        <br />
    </div>


    <div class="container">
        <h5 style="color:green"><label>@TempData["message"]</label></h5>
        <br />

        <form method="post" asp-controller="LOC_MST_ContactCategory" asp-action="Save">
            @Html.HiddenFor(x=>x.ContactCategoryID)
            <div class="row" style="align-items:center">
                <div class="col-md-2">
                    <span style="color: #ff0000">*</span>
                    ContactCategory Name :-
                </div>
                <div class="col-md-3">
                    <input type="text" placeholder="Enter ContactCategory Name" asp-for="ContactCategoryName" class="form-control" />
                    <span asp-validation-for="ContactCategoryName" class="text-danger"></span>
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-md-2">
                    Creation Date :-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter Creation Date" asp-for="CreationDate" class="form-control" />
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-2">
                    Modification Date :-
                </div>
                <div class="col-md-3">
                    <input type="date" placeholder="Enter Modification Date" asp-for="Modification" class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Save" asp-controller="LOC_MST_ContactCategory" asp-action="Save" class="btn btn-a" />
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Cancel" asp-controller="LOC_MST_ContactCategory" asp-action="Index" class="btn btn-b" />
                </div>
            </div>
        </form>

    </div>
</section>

@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/LOC_MST_ContactCategory/LOC_MST_ContactCategoryList.cshtml
@{
    ViewData["Title"] = "State List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data
@model DataTable

<div class="row">
    <div class="col col-md-10">
        <h1>ContactCategory List</h1>
    </div>
    <div class="pull-right">
        <div id="sample_1_filter" class="dataTables_filter">
            <label><input type="text" class="form-control input-sm input-small input-inline" placeholder="Search" id="sample_1" aria-controls="sample_1" /></label>
        </div>
    </div>
    <div class="col col-md-2">
        <a class="btn btn-success" asp-controller="LOC_MST_ContactCategory" asp-action="Add">ADD LIST</a>
    </div>
</div>
<hr />

<table class="table" id="sample_1">
    <thead>
        <tr>
            @*<th scope="col">ContactCategory ID        </th>*@
            <th scope="col">ContactCategory Name      </th>
            <th scope="col">CreationDate </th>
            <th scope="col">Modification </th>
            <th scope="col" colspan="2" class="text-center">Action</th>

        </tr>
    </thead>
    <tbody id="sample_2">
        @foreach (DataRow dr in Model.Rows)

        {
            <tr>

                @*<th scope="col">@dr["ContactCategoryID"]</th>*@
                <td scope="col"> @dr["ContactCategoryName"]   </td>
                <td scope="col"> @Convert.ToDateTime(dr["CreationDate"]).ToString("dd-MM-yyyy")</td>
                <td scope="col"> @Convert.ToDateTime(dr["Modification"]).ToString("dd-MM-yyyy")</td>
                <td scope="col">
                    <form method="post" asp-controller="LOC_MST_ContactCategory" asp-action="Delete">
                        <input type="hidden" name="ContactCategoryID" value="@Convert.ToInt32(dr["ContactCategoryID"])" />
                        <button type="submit" class="btn btn-danger" onclick="return confirm ('Are you sure you want to delete : @dr["ContactCategoryName"]')">Delete</button>
                    </form>
                </td>
                <td scope="col">
                    <form method="post" asp-controller="LOC_MST_ContactCategory" asp-action="Add">
                        <input type="hidden" name="ContactCategoryID" value="@Convert.ToInt32(dr["ContactCategoryID"])" />
                        <button type="submit" class="btn btn-success" >Edit</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}